FROM alpine:3.15
LABEL maintainer="Victor Castell <victor@victorcastell.com>"

RUN set -x && \
	buildDeps='bash ca-certificates openssl tzdata' && \
	apk add --no-cache --update $buildDeps && \
    adduser -D -u 12345 -g 12345 bs6
COPY bs6 /usr/bin/

USER 12345
WORKDIR /home/bs6

ENTRYPOINT ["b6"]
